CREATE TABLE IF NOT EXISTS firm_profile (
  id BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (id = TRUE),
  business_name VARCHAR(255) NOT NULL,
  ein VARCHAR(40) NOT NULL DEFAULT '',
  ptin VARCHAR(40) NOT NULL DEFAULT '',
  office_code VARCHAR(80) NOT NULL DEFAULT '',
  reviewer_name VARCHAR(255) NOT NULL DEFAULT '',
  reviewer_title VARCHAR(255) NOT NULL DEFAULT '',
  phone VARCHAR(50) NOT NULL DEFAULT '',
  email VARCHAR(255) NOT NULL DEFAULT '',
  address TEXT NOT NULL DEFAULT '',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
