'use client';

import { useEffect, useState } from 'react';

type Props = { applicationId: string; token: string };
export default function CaseManagementPanel({ applicationId, token }: Props) {
  const [data, setData] = useState<any>(null); const [error, setError] = useState(''); const [staff, setStaff] = useState(''); const [note, setNote] = useState(''); const [visibility, setVisibility] = useState('INTERNAL');
  const load = async () => { try { const res = await fetch(`/api/admin/applications/${applicationId}/case-management`, { headers: { 'x-admin-token': token } }); const body = await res.json(); if (!res.ok) throw new Error(body.error); setData(body); setStaff(body.caseManagement.assigned_staff || ''); } catch (e: any) { setError(e.message); } };
  useEffect(() => { load(); }, [applicationId]);
  const act = async (action: string, extra: Record<string, string> = {}) => { setError(''); try { const res = await fetch(`/api/admin/applications/${applicationId}/case-management`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-admin-token': token }, body: JSON.stringify({ action, ...extra }) }); const body = await res.json(); if (!res.ok) throw new Error(body.error); setNote(''); await load(); } catch (e: any) { setError(e.message); } };
  return <section className="mb-6 grid gap-4 lg:grid-cols-3"><div className="glass-card p-4"><h2 className="font-bold text-white">Case assignment</h2><input value={staff} onChange={(e) => setStaff(e.target.value)} placeholder="Assigned staff member" className="mt-3 w-full rounded-lg bg-abyss-panel p-2 text-xs text-white"/><button onClick={() => act('assign', { assignedStaff: staff })} className="mt-2 rounded-lg border border-mint-500/50 px-3 py-2 text-xs font-semibold text-mint-300">Save assignment</button>{data?.caseManagement.archived_at ? <div className="mt-4 rounded-lg bg-red-950/40 p-3 text-xs text-red-200">Archived: {data.caseManagement.archived_reason}<button onClick={() => act('restore')} className="mt-2 block font-semibold text-mint-300">Restore case</button></div> : <button onClick={() => { const reason = window.prompt('Archive reason'); if (reason) act('archive', { reason }); }} className="mt-4 text-xs font-semibold text-red-300">Archive case</button>}</div><div className="glass-card p-4"><h2 className="font-bold text-white">Case notes</h2><textarea value={note} onChange={(e) => setNote(e.target.value)} placeholder="Internal note" className="mt-3 min-h-20 w-full rounded-lg bg-abyss-panel p-2 text-xs text-white"/><select value={visibility} onChange={(e) => setVisibility(e.target.value)} className="mt-2 rounded-lg bg-abyss-panel p-2 text-xs"><option value="INTERNAL">Internal only</option><option value="CLIENT">Client-visible</option></select><button onClick={() => act('note', { note, visibility })} disabled={!note.trim()} className="ml-2 rounded-lg border border-mint-500/50 px-3 py-2 text-xs font-semibold text-mint-300 disabled:opacity-40">Add note</button><div className="mt-3 max-h-32 space-y-2 overflow-auto">{data?.notes.map((n: any) => <p key={n.id} className="rounded bg-abyss-panel p-2 text-xs text-slate-300">{n.body}<span className="ml-2 text-[10px] text-slate-500">{n.visibility.toLowerCase()}</span></p>)}</div></div><div className="glass-card p-4"><h2 className="font-bold text-white">Status history</h2><div className="mt-3 max-h-44 space-y-2 overflow-auto">{data?.history.length ? data.history.map((h: any) => <p key={h.id} className="border-b border-white/10 pb-2 text-xs text-slate-300">{h.next_status.replace(/_/g, ' ')}<span className="block text-[10px] text-slate-500">{new Date(h.created_at).toLocaleString()}</span></p>) : <p className="text-xs text-slate-500">No history yet.</p>}</div>{error && <p className="mt-3 text-xs text-red-300">{error}</p>}</div></section>;
}
