'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import AdminSidebarShell from '../../../components/admin/AdminSidebarShell';
import { useAdminAuth } from '../../../lib/useAdminAuth';

type Client = { id: string; first_name: string; last_name: string; email: string };
type Invoice = { id: string; client_id: string | null; application_id: string | null; description: string | null; amount_cents: number; amount_paid_cents: number; payment_status: string; square_payment_link: string | null; created_at: string; first_name: string | null; last_name: string | null; email: string | null };

export default function PaymentsPage() {
  const { token, ready } = useAdminAuth();
  const [clients, setClients] = useState<Client[]>([]); const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [clientId, setClientId] = useState(''); const [amount, setAmount] = useState(''); const [description, setDescription] = useState('PATSL service fee'); const [message, setMessage] = useState(''); const [filter, setFilter] = useState('ALL');
  const load = async () => { if (!token) return; const h = { 'x-admin-token': token }; const [c, i] = await Promise.all([fetch('/api/admin/clients', { headers: h }), fetch('/api/admin/payments', { headers: h })]); const cd = await c.json(), id = await i.json(); if (!c.ok || !i.ok) throw new Error(cd.error || id.error || 'Failed to load accounting data.'); setClients(cd.clients || []); setInvoices(id.invoices || []); };
  useEffect(() => { load().catch((e) => setMessage(e.message)); }, [token]);
  const totals = useMemo(() => invoices.reduce((sum, i) => ({ invoiced: sum.invoiced + i.amount_cents, collected: sum.collected + i.amount_paid_cents }), { invoiced: 0, collected: 0 }), [invoices]);
  const visible = invoices.filter((i) => filter === 'ALL' || i.payment_status === filter);
  async function create(e: FormEvent) { e.preventDefault(); setMessage(''); try { const r = await fetch('/api/admin/payments/create-link', { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-admin-token': token! }, body: JSON.stringify({ clientId, amount, description }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setMessage(d.emailSent ? 'Invoice created and payment link emailed.' : 'Invoice created, but client email was not sent.'); setAmount(''); await load(); } catch (e: any) { setMessage(e.message); } }
  async function record(id: string) { const value = window.prompt('Amount received (USD)'); if (!value) return; const method = window.prompt('Payment method', 'Cash') || 'Manual'; try { const r = await fetch(`/api/admin/payments/${id}/record`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-admin-token': token! }, body: JSON.stringify({ amount: value, method }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); await load(); } catch (e: any) { setMessage(e.message); } }
  if (!ready) return <div className="min-h-screen bg-ink-950" />;
  return <AdminSidebarShell title="Accounting & billing" subtitle="Invoices, collections, outstanding balances, and customer payment history in one ledger.">
    <div className="mb-5 grid gap-3 sm:grid-cols-3"><Metric label="Invoices" value={`$${(totals.invoiced / 100).toFixed(2)}`} /><Metric label="Collected" value={`$${(totals.collected / 100).toFixed(2)}`} /><Metric label="Outstanding" value={`$${((totals.invoiced - totals.collected) / 100).toFixed(2)}`} /></div>
    <div className="grid gap-5 lg:grid-cols-[340px_1fr]"><form onSubmit={create} className="glass-card space-y-3 p-5"><h2 className="font-bold">New invoice</h2><p className="text-xs text-slate-400">Create a secure payment link for a customer.</p><select required value={clientId} onChange={(e) => setClientId(e.target.value)} className="w-full rounded-lg bg-abyss-panel p-2 text-sm"><option value="">Select customer</option>{clients.map((c) => <option key={c.id} value={c.id}>{c.first_name} {c.last_name} — {c.email}</option>)}</select><input required type="number" min="1" max="10000" step="0.01" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="Amount (USD)" className="w-full rounded-lg bg-abyss-panel p-2 text-sm"/><input required maxLength={120} value={description} onChange={(e) => setDescription(e.target.value)} className="w-full rounded-lg bg-abyss-panel p-2 text-sm"/><button className="btn-pill-primary w-full">Create & email payment link</button>{message && <p className="text-xs text-slate-300">{message}</p>}</form>
      <div className="glass-card overflow-hidden"><div className="flex items-center justify-between p-4"><h2 className="font-bold">Orders & payments</h2><select value={filter} onChange={(e) => setFilter(e.target.value)} className="rounded-lg bg-abyss-panel p-2 text-xs"><option value="ALL">All payments</option><option value="PENDING">Pending</option><option value="PARTIAL">Partial</option><option value="PAID">Paid</option></select></div><table className="w-full text-left text-xs"><thead className="text-slate-400"><tr><th className="p-3">Customer / order</th><th>Total</th><th>Paid</th><th>Balance</th><th>Status</th><th /></tr></thead><tbody>{visible.map((i) => { const balance = i.amount_cents - i.amount_paid_cents; return <tr key={i.id} className="border-t border-white/10"><td className="p-3">{i.client_id ? <Link href={`/admin/clients/${i.client_id}`} className="font-semibold text-white hover:text-mint-300">{i.first_name} {i.last_name}</Link> : <b>{i.first_name} {i.last_name}</b>}<br/><span className="text-slate-400">{i.description || 'Service fee'}</span></td><td>${(i.amount_cents / 100).toFixed(2)}</td><td>${(i.amount_paid_cents / 100).toFixed(2)}</td><td>${(balance / 100).toFixed(2)}</td><td>{i.payment_status}</td><td className="p-3">{balance > 0 && <button onClick={() => record(i.id)} className="text-mint-300">Record payment</button>} {i.square_payment_link && <a className="ml-2 text-mint-300" href={i.square_payment_link} target="_blank" rel="noreferrer">Link</a>}</td></tr>; })}</tbody></table></div></div>
  </AdminSidebarShell>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="glass-card p-4"><p className="text-[10px] font-semibold uppercase text-slate-500">{label}</p><p className="mt-1 text-xl font-bold text-white">{value}</p></div>; }
