'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import AdminSidebarShell from '../../../components/admin/AdminSidebarShell';
import { useAdminAuth } from '../../../lib/useAdminAuth';

type Data = { summary: { invoicedCents: number; collectedCents: number; receivableCents: number; expenseCents: number; netIncomeCents: number }; invoices: any[]; expenses: any[]; transactions: any[] };
const money = (n: number) => `$${(n / 100).toFixed(2)}`;

export default function AccountingPage() {
  const { token, ready } = useAdminAuth(); const [data, setData] = useState<Data | null>(null); const [error, setError] = useState(''); const [from, setFrom] = useState(new Date(new Date().getFullYear(), 0, 1).toISOString().slice(0, 10)); const [to, setTo] = useState(new Date().toISOString().slice(0, 10)); const [expense, setExpense] = useState({ expenseDate: new Date().toISOString().slice(0, 10), category: 'Software', description: '', amount: '' });
  const load = async () => { if (!token) return; try { const res = await fetch(`/api/admin/accounting?from=${from}&to=${to}`, { headers: { 'x-admin-token': token } }); const body = await res.json(); if (!res.ok) throw new Error(body.error); setData(body); } catch (e: any) { setError(e.message); } };
  useEffect(() => { load(); }, [token, from, to]);
  const exportCsv = () => { if (!data) return; const lines = ['Date,Type,Category,Description,Customer,Amount']; data.transactions.forEach((x) => lines.push(`${x.received_at},Income,${x.payment_method},"${x.description || ''}","${x.first_name || ''} ${x.last_name || ''}",${(x.amount_cents / 100).toFixed(2)}`)); data.expenses.forEach((x) => lines.push(`${x.expense_date},Expense,${x.category},"${x.description}",,${(-x.amount_cents / 100).toFixed(2)}`)); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([lines.join('\n')], { type: 'text/csv' })); a.download = `patsl-accounting-${from}-to-${to}.csv`; a.click(); URL.revokeObjectURL(a.href); };
  const addExpense = async (e: FormEvent) => { e.preventDefault(); try { const res = await fetch('/api/admin/accounting', { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-admin-token': token! }, body: JSON.stringify(expense) }); const body = await res.json(); if (!res.ok) throw new Error(body.error); setExpense({ ...expense, description: '', amount: '' }); await load(); } catch (e: any) { setError(e.message); } };
  if (!ready) return <div className="min-h-screen bg-ink-950" />;
  return <AdminSidebarShell title="Accounting reports" subtitle="Income, expenses, receivables, profit and loss, balance sheet, and exportable transaction reports.">{error && <p className="mb-3 rounded-lg bg-red-950 p-3 text-sm text-red-300">{error}</p>}<div className="mb-4 flex flex-wrap gap-2"><input type="date" value={from} onChange={(e) => setFrom(e.target.value)} className="rounded-lg bg-abyss-panel p-2 text-xs"/><input type="date" value={to} onChange={(e) => setTo(e.target.value)} className="rounded-lg bg-abyss-panel p-2 text-xs"/><button onClick={exportCsv} className="rounded-lg border border-mint-500/50 px-3 text-xs font-semibold text-mint-300">Export CSV</button></div>{data && <><div className="mb-5 grid gap-3 sm:grid-cols-5"><Card title="Sales" value={money(data.summary.invoicedCents)} /><Card title="Cash collected" value={money(data.summary.collectedCents)} /><Card title="Accounts receivable" value={money(data.summary.receivableCents)} /><Card title="Expenses" value={money(data.summary.expenseCents)} /><Card title="Net income" value={money(data.summary.netIncomeCents)} /></div><div className="grid gap-5 lg:grid-cols-2"><section className="glass-card p-5"><h2 className="font-bold">Profit & loss</h2><dl className="mt-4 space-y-2 text-sm"><Row label="Income collected" value={money(data.summary.collectedCents)} /><Row label="Less expenses" value={`-${money(data.summary.expenseCents)}`} /><Row label="Net income" value={money(data.summary.netIncomeCents)} /></dl><h2 className="mt-6 font-bold">Balance sheet</h2><dl className="mt-4 space-y-2 text-sm"><Row label="Accounts receivable" value={money(data.summary.receivableCents)} /><Row label="Cash collected in selected period" value={money(data.summary.collectedCents)} /></dl></section><form onSubmit={addExpense} className="glass-card space-y-3 p-5"><h2 className="font-bold">Record expense</h2><input type="date" value={expense.expenseDate} onChange={(e) => setExpense({ ...expense, expenseDate: e.target.value })} className="w-full rounded-lg bg-abyss-panel p-2 text-xs"/><select value={expense.category} onChange={(e) => setExpense({ ...expense, category: e.target.value })} className="w-full rounded-lg bg-abyss-panel p-2 text-xs">{['Advertising','Bank fees','Contractors','Insurance','Office','Payroll','Professional services','Software','Taxes','Travel','Other'].map((c) => <option key={c}>{c}</option>)}</select><input required placeholder="Description" value={expense.description} onChange={(e) => setExpense({ ...expense, description: e.target.value })} className="w-full rounded-lg bg-abyss-panel p-2 text-xs"/><input required type="number" min="0.01" step="0.01" placeholder="Amount" value={expense.amount} onChange={(e) => setExpense({ ...expense, amount: e.target.value })} className="w-full rounded-lg bg-abyss-panel p-2 text-xs"/><button className="btn-pill-primary w-full">Save expense</button></form></div></>}</AdminSidebarShell>;
}
function Card({ title, value }: { title: string; value: string }) { return <div className="glass-card p-4"><p className="text-[10px] uppercase text-slate-500">{title}</p><p className="mt-1 text-lg font-bold text-white">{value}</p></div>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex justify-between border-b border-white/10 pb-2"><dt className="text-slate-400">{label}</dt><dd className="font-semibold text-white">{value}</dd></div>; }
